version: '3'
services:
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - php
    networks:
      - app
    ports:
      - '180:80'
    volumes:
      - ./nginx/conf.conf:/opt/bitnami/nginx/conf/server_blocks/conf.conf
  php:
    image: 'bitnami/php-fpm:latest'
    networks:
      - app
    volumes:
      - ./symfony:/app
  mariadb:
    image: 'mariadb:latest'
    networks:
      - app
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./mariadb/data:/var/lib/mysql
  # rabbit


networks:
  app:
    driver: bridge
