version: '3'
services:
  nginx:
    container_name: 'nginx'
    image: 'bitnami/nginx:latest'
    depends_on:
      - fpm
    networks:
      - app
    ports:
      - '180:80'
    volumes:
      - ./nginx/conf.conf:/opt/bitnami/nginx/conf/server_blocks/conf.conf
  fpm:
    container_name: 'fpm'
    image: 'php-fpm-custom:latest'
    networks:
      - app
    volumes:
      - ./symfony:/app
      - ./fpm/custom.ini:/opt/bitnami/php/etc/conf.d/custom.ini
  database:
    container_name: 'database'
    image: 'mariadb:latest'
    networks:
      - app
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: sTlInaYSVdVnmv9uYI2gfj
    volumes:
      - ./mariadb/data:/var/lib/mysql
  rabbit:
    container_name: 'rabbit'
    image: 'bitnami/rabbitmq:latest'
    networks:
      - app
    ports:
      - '5672:5672'
    environment:
      RABBITMQ_USERNAME: 'root'
      RABBITMQ_PASSWORD: 'sTlInaYSVdVnmv9uYI2gfj'


networks:
  app:
    driver: bridge
