version: '3'
services:
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - php
    networks:
      - app
    ports:
      - '180:80'
    volumes:
      - ./nginx/conf.conf:/opt/bitnami/nginx/conf/server_blocks/conf.conf
  php:
    image: 'bitnami/php-fpm:latest'
    networks:
      - app
    volumes:
      - ./symfony/public:/app
  # maridb
  # rabbit


networks:
  app:
    driver: bridge
