version: '3'
services:
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - php
    networks:
      - app
    ports:
      - '80:80'
      - '443:433'
    volumes:
      - /nginx/conf.conf:/opt/bitnami/nginx/conf/server_blocks/conf.conf
  php:
    image: 'bitnami/php-fpm:latest'
    networks:
      - app
    volumes:
      - /symfony/public:/app
  # maridb
  # rabbit


netwokrs:
  app:
    driver: bridge
